DROP TABLE IF EXISTS User;
CREATE TABLE User (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL, avatar TEXT NOT NULL, introduction TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL);
DROP TABLE IF EXISTS Directory;
CREATE TABLE Directory (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, type INTEGER NOT NULL, parentID INTEGER, user INTEGER NOT NULL);
DROP TABLE IF EXISTS File;
CREATE TABLE File(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT, parentID INTEGER NOT NULL, path TEXT NOT NULL, user INTEGER NOT NULL, format TEXT NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL)